export type AdminTab =
  | 'overview'
  | 'users'
  | 'roles'
  | 'permissions'
  | 'tenants'
  | 'plans'
  | 'subscriptions'
  | 'billing'
  | 'logs'
  | 'services'
  | 'backups'
  | 'jobs'
  | 'reports'
  | 'notifications'
  | 'webhooks'
  | 'api-keys'
  | 'feature-flags'
